// <auto-generated />
using AlienigenasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlienigenasAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230830192901_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlienigenasAPI.Models.Alien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("CorpoDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaNaTerra")
                        .HasColumnType("bit");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanetaOrigemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanetaOrigemId");

                    b.ToTable("Aliens");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.Planeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Populacao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Planetas");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.Poder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poderes");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.PoderAlien", b =>
                {
                    b.Property<int>("AlienId")
                        .HasColumnType("int");

                    b.Property<int>("PoderId")
                        .HasColumnType("int");

                    b.HasKey("AlienId", "PoderId");

                    b.HasIndex("PoderId");

                    b.ToTable("PoderesAliens");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.Alien", b =>
                {
                    b.HasOne("AlienigenasAPI.Models.Planeta", "PlanetaOrigem")
                        .WithMany()
                        .HasForeignKey("PlanetaOrigemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanetaOrigem");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.PoderAlien", b =>
                {
                    b.HasOne("AlienigenasAPI.Models.Alien", "Alien")
                        .WithMany("PoderesAlien")
                        .HasForeignKey("AlienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlienigenasAPI.Models.Poder", "Poder")
                        .WithMany("PoderesAlien")
                        .HasForeignKey("PoderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alien");

                    b.Navigation("Poder");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.Alien", b =>
                {
                    b.Navigation("PoderesAlien");
                });

            modelBuilder.Entity("AlienigenasAPI.Models.Poder", b =>
                {
                    b.Navigation("PoderesAlien");
                });
#pragma warning restore 612, 618
        }
    }
}
